// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFXg1jW7dQlP4j12yefSC3FpUtvOywBYQ',
    appId: '1:704061368751:web:a63ae0dbefab6bfcd2275a',
    messagingSenderId: '704061368751',
    projectId: 'blood-donation-61122',
    authDomain: 'blood-donation-61122.firebaseapp.com',
    storageBucket: 'blood-donation-61122.appspot.com',
    measurementId: 'G-CQ8NH4RN42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMLLheDUYIhA7NI4VYWFfBO6UqxM3mB2M',
    appId: '1:704061368751:android:1d66777e49af39acd2275a',
    messagingSenderId: '704061368751',
    projectId: 'blood-donation-61122',
    storageBucket: 'blood-donation-61122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNNVV3ciP85s8koxg2Nf45beG4XCiv9mE',
    appId: '1:704061368751:ios:5a79491df14b7616d2275a',
    messagingSenderId: '704061368751',
    projectId: 'blood-donation-61122',
    storageBucket: 'blood-donation-61122.appspot.com',
    iosBundleId: 'com.example.lifeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNNVV3ciP85s8koxg2Nf45beG4XCiv9mE',
    appId: '1:704061368751:ios:5a79491df14b7616d2275a',
    messagingSenderId: '704061368751',
    projectId: 'blood-donation-61122',
    storageBucket: 'blood-donation-61122.appspot.com',
    iosBundleId: 'com.example.lifeflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFXg1jW7dQlP4j12yefSC3FpUtvOywBYQ',
    appId: '1:704061368751:web:25686a653501974dd2275a',
    messagingSenderId: '704061368751',
    projectId: 'blood-donation-61122',
    authDomain: 'blood-donation-61122.firebaseapp.com',
    storageBucket: 'blood-donation-61122.appspot.com',
    measurementId: 'G-VEMR59M5F2',
  );

}